name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build, test and install with Maven
      run: mvn clean install --no-transfer-progress
      env:
        # If your tests require any environment variables, add them here
        # For example:
        # AI_API_KEY: ${{ secrets.AI_API_KEY }}
        # AI_API_ENDPOINT: ${{ secrets.AI_API_ENDPOINT }}
